site_name: Ciência da Computação
repo_name: brunoruas2/ciencia_computacao
repo_url: https://github.com/brunoruas2/ciencia_computacao
site_url: https://brunoruas2.github.io/CC_site/
copyright: Bruno de Melo Ruas

nav:
    - Bem Vindos: index.md
    - PUC:
      - Eixo 1:
        - Algoritmo e Abstração: nav\PUC\eixo1\algoritmos_e_abstracao.md
        - Algoritmo e Lógica: nav\PUC\eixo1\algoritmos_e_logica.md
        - Desenvolvimento Web Frontend: nav\PUC\eixo1\desenvolvimento_web.md
        - Matemática Básica: nav\PUC\eixo1\matematica_basica.md
        - Organização de Computadores: nav\PUC\eixo1\organizacao_computadores.md
        - Fundamentos de Eng. de Software: nav\PUC\eixo1\fundamentos_eng_soft.md
        - Pensamento Computacional: nav\PUC\eixo1\pensamento_comp.md
        - Lógica Computacional: nav\PUC\eixo1\logica_comp.md
        - Projeto 1 - Web Fron-End: nav\PUC\eixo1\projeto_dev_web_frontend.md
    - Tech: nav/tech.md

theme:
  name: simple-blog
  favicon: assets/logo.png
  logo: assets/logo.png
  theme_style: light
  site_name_style: normal
  title_style: bold
  colors:
    text: black
    title: black
    primary: black
    background: white
  components:
    site_name: true
    title: true
    menu: true
    preview: true
    footer: true

extra_css:
  - css/custom.css

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  # tab content block
  - attr_list
  - md_in_html
  - pymdownx.superfences
  # check list
  - pymdownx.tabbed
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  # latex syntax
  - pymdownx.arithmatex:
      generic: true
  # footnote
  - footnotes
