site_name: Ciência da Computação
repo_name: brunoruas2/ciencia_computacao
repo_url: https://github.com/brunoruas2/ciencia_computacao
site_url: https://brunoruas2.github.io/CC_site/
copyright: Bruno de Melo Ruas

nav:
    - Bem Vindos: index.md
    - Tech Info: nav/tech.md
    - PUC:
      - Eixo 1:
        - Algoritmo e Abstração: nav\PUC\eixo1\algoritmos_e_abstracao.md
        - Algoritmo e Lógica: nav\PUC\eixo1\algoritmos_e_abstracao.md

theme:
  name: simple-blog
  favicon: assets/logo.png
  logo: assets/logo.png
  theme_style: light
  site_name_style: normal
  title_style: bold
  colors:
    text: black
    title: black
    primary: black
    background: white
  components:
    site_name: true
    title: true
    menu: true
    preview: true
    footer: true

extra_css:
  - css/custom.css

markdown_extensions:
  # tab content block
  - attr_list
  - md_in_html
  - pymdownx.superfences
  # check list
  - pymdownx.tabbed
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
